#!/bin/sh

if [[ -f ~/.Xdefaults ]]; then
    xrdb -quiet -load < ~/.Xdefaults &
fi

# After copying new fonts into this directory, run `mkfontdir` and `mkfontscale` there
if [[ -d $HOME/.fonts ]]; then
    xset +fp $HOME/.fonts
    xset fp rehash
fi

backlighter day

# Set in /etc/X11/xorg.conf.d
#   xset s off -dpms
#   synclient TouchpadOff=1 ClickPad=0 FingerHigh=... FingerLow=... PalmDetect=... PalmMinZ=...
#
# syndaemon - a program that monitors keyboard activity and
# disables the touchpad when the keyboard is being used.
#   -i  <idle-time> How many seconds to wait after the last
#                   key press before enabling the touchpad.
#   -K  Ignore modifier keys and Modifier+Key combos
#   -d  Start as a daemon
syndaemon -i 0.35 -K -d

case $1 in
    dwm|*xprofile)

        if which picom >/dev/null 2>&1 && ! pgrep -u $USER picom >/dev/null 2>&1; then
            picom --daemon
        fi

        # Use PipeWire instead of Pulse
        # Take steps to prevent Pulse from launching at startup
        if [[ -d ~/.config/pulse || -f ~/.config/pulse/client.conf ]] \
            || ! grep -qE "autospawn *= *no"; then
            mkdir -p ~/.config/pulse
            echo "autospawn = no" > ~/.config/pulse/client.conf
        fi

        # Boot up PipeWire processes
        for daemon in pipewire pipewire-pulse wireplumber; do
            /usr/bin/daemon -rB --pidfiles=~/.run --name=$daemon /usr/bin/$daemon
        done

        if ! pgrep -u $USER dwm-statusbar; then
            dwm-statusbar &
        fi

        if [[ -x ~/.wallpapers/cycle/next-wallpaper.sh ]]; then
            ~/.wallpapers/cycle/next-wallpaper.sh &
        fi

        # Make Java apps work in DWM
        _JAVA_AWT_WM_NONREPARENTING=1
        export _JAVA_AWT_WM_NONREPARENTING
        ;;
esac

# vim: set expandtab tabstop=4:
