#!/bin/sh

if [ -f ~/.Xdefaults ]; then
    xrdb -quiet -load < ~/.Xdefaults &
fi

# After copying new fonts into this directory, run `mkfontdir` and `mkfontscale` there
if [ -d $HOME/.fonts ]; then
    xset fp+ $HOME/.fonts
    xset fp rehash
fi

setxkbmap colehack,us -option grp:ctrls_toggle -option grp_led:scroll &

# "Screensaver? We don't need no stinkin' screensaver!"
xset s off -dpms

case $1 in
	dwm)
		# set the variable USE_COMPTON to non-null to use compton
		case ${USE_COMPTON=no} in
			no)
				if ! pgrep -u $USER picom; then
					picom &
				fi
				;;
			*)
				if ! pgrep -u $USER compton; then
					compton -b
				fi
				;;
		esac

		if ! pgrep -u $USER dwm-statusbar; then
            dwm-statusbar&
        fi

        if [ -x ~/.wallpapers/cycle/next-wallpaper.sh ]; then
            ~/.wallpapers/cycle/next-wallpaper.sh &
        fi

		# xrandr --output DP2 --right-of DP1 &
		;;
esac
