#!/bin/sh

xrdb -quiet -load < ~/.Xdefaults &

setxkbmap colehack,us -option grp:ctrls_toggle -option grp_led:scroll &

case $1 in
	dwm)
		compton &
		dwm-statusbar &
		~/.wallpapers/cycle/next-wallpaper.sh &
		xrandr --output DP2 --right-of DP1 &
		;;
esac
